### ISSUE TITLE
InvalidSchema error running kcontrol

### ISSUE THREAD

**Issue by thorstenkampe** [ragnarlonn/k6control#2]
```
python.exe k6control.py -a localhost:6565
```
```
Traceback (most recent call last):
  File "k6control.py", line 293, in <module>
    main()
  File "k6control.py", line 46, in main
    curses.wrapper(run)
  File "F:\PortableApps\Python\lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "k6control.py", line 63, in run
    k6.fetch_data()
  File "k6control.py", line 146, in fetch_data
    self.fetch_status()
  File "k6control.py", line 136, in fetch_status
    r = requests.get(self.k6_address + "/v1/status")
  File "F:\PortableApps\Python\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "F:\PortableApps\Python\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\PortableApps\Python\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\PortableApps\Python\lib\site-packages\requests\sessions.py", line 616, in send
    adapter = self.get_adapter(url=request.url)
  File "F:\PortableApps\Python\lib\site-packages\requests\sessions.py", line 707, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'localhost:6565/v1/status'
```

**Comment by ragnarlonn** [comment]
@thorstenkampe Try specifying the protocol also, like `python.exe k6control.py -a http://localhost:6565`

**Comment by thorstenkampe** [comment]
Ah, okay. My invocation came directly from the Usage chapter of k6control's home page (https://github.com/ragnarlonn/k6control). On the other hand, `http://localhost:6565` is the default so that is superfluous.

**Comment by teward** [comment]
Using https://k6.io/blog/building-a-ui-for-the-k6-load-testing-tool as a guide I was able to get k6control to work.  However, k6control as written is a Python 2 application; it needs Python 3 revisions since Python 2 is effectively End of Life.

I've got a PR for Python 3 support, but if that doesn't help or this is effectively considered a 'dead project', I have my fork of https://github.com/teward/k6control which is Python 3 compatible and fixes the other issues observed.
