### ISSUE TITLE
curses error: TypeError: integer argument expected, got float

### ISSUE THREAD

**Issue by thorstenkampe** [ragnarlonn/k6control#3]
```
Traceback (most recent call last):
  File "k6control.py", line 293, in <module>
    main()
  File "k6control.py", line 46, in main
    curses.wrapper(run)
  File "F:\PortableApps\Python\lib\curses\__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "k6control.py", line 70, in run
    status_window = StatusWindow(stdscr)
  File "k6control.py", line 215, in __init__
    self.resize()
  File "k6control.py", line 220, in resize
    self.win = self.stdscr.subwin(self.height, self.width, 0, 0)
TypeError: integer argument expected, got float
```

**Comment by thorstenkampe** [comment]
Same in line 226

**Comment by thorstenkampe** [comment]
and in line 250
